### ISSUE TITLE
Jekyll docs command fails in jekyll project

### ISSUE THREAD

**Issue by tithamane** [jekyll/jekyll-docs#14]
I don't know if this should be a jekyll or jekyll docs issue but this is something that I find a little annoying. A few months back it made me give up on this gem but today I found a way around.

If you run `jekyll docs` inside a jekyll project it fails and tell you to install the gem. To get this to work, you have to run the command outside of a jekyll project. 

<img width="803" alt="screen shot 2016-09-14 at 7 29 14 pm" src="https://cloud.githubusercontent.com/assets/5633403/18522822/e835ec0e-7ab1-11e6-841c-1d8cdde0ee51.png">

Maybe this is mentioned somewhere but it would be nice if it mentioned on the read me.

**Comment by bryanjhv** [comment]
That's because the Jekyll [binary](https://github.com/jekyll/jekyll/blob/v3.1.6/bin/jekyll#L9) calls `Bundler.setup` in the [plugin manager](https://github.com/jekyll/jekyll/blob/v3.1.6/lib/jekyll/plugin_manager.rb#L30-L43) and as you don't have a `gem 'jekyll-docs'` in your `Gemfile` it will just fail (Bundler, not Jekyll).

Workarounds:
* Run `jekyll docs` outside a directory containing `Gemfile`.
* Set env variable `JEKYLL_NO_BUNDLER_REQUIRE=true`.

**Comment by DirtyF** [comment]
[Warning](https://github.com/jekyll/jekyll-docs/blob/master/README.md#usage) added in the README.
